# What?
  * Nympy is the findamental pacjage for scientific commputing in Python
  * the numpy array is an n-dimensional array
  * Numpy methods allow for fast and simple linear algebra and data processing tasks
  
# So What?
  * Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
  * Super fast. Nimpy arrays are implemented in C, which makes nimpy very fast
  * Numpy is the most popular linear algebra library for Python
  * Provides loop_like behavior w/o the overhead of loops or list comprehension (vectorized operations)
  * Provides list + loop + conditional behavior for filltering arrays
  
# Now What?

  * Start working with numpy arrays! np.array([1, 2, 3]) to create an array
  * We'll start ising buolt-in numpy functions all the time:
      * min, mac, mean, sum, std
      * np.median
  * Learn to use some vectorized operations
  * Learn how to create arrays of booleans to filter results
  

In [1]:
# import the library in order to actually use it

import numpy as np

# import pandas as pd

In [2]:
%%timeit

UsageError: %%timeit is a cell magic, but the cell body is empty. Did you mean the line magic %timeit (single %)?


In [3]:
%%timeit
[x ** 2 for x in range(1, 1_000_001)]

210 ms ± 1.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [101]:
%%timeit
# numpy equivalent:
# make a numpy array from on to a million,
# take that whole thing, square it

np.arange(1, 1_000_001) ** 2

1.03 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Getting Started
  * The np.array method converts iterables and collections into numpy arrays
  * The numpy array is n-dimensional, which means it's flexible.

In [5]:
# Let's make our first numpy array
# maka list x
x = [1, 2, 3, 4, 5]
x = np.array(x)
x, type(x)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [6]:
y = [1, 2, 3, 4, 5]
y.shape

AttributeError: 'list' object has no attribute 'shape'

In [7]:
x.shape

(5,)

the np.array method converts Python collections into numpy arrays of the appropriate dimension

In [8]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [9]:
type(matrix)

numpy.ndarray

In [39]:
dtype(matrix)

NameError: name 'dtype' is not defined

In [11]:
# zero indexed
matrix[0]

array([1, 2, 3])

In [12]:
matrix[0, 2]

3

In [ ]:
# axes: [row, col]
# pneumonic...
# r0ws, co1s

In [14]:
first_row = matrix[0]
first_row

array([1, 2, 3])

In [15]:
x

array([1, 2, 3, 4, 5])

In [16]:
x[0:3]

array([1, 2, 3])

In [17]:
a = np.array(range(1, 100))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
a.sum(), a.mean(), a.min(), a.max(), a.std()

(4950, 50.0, 1, 99, 28.577380332470412)

In [19]:
np.median(a)

50.0

In [20]:
# true and false assertions
smalllist = [1, 3, 5]
newlist = []
for el in smalllist:
    if el in (1, 5):
        newlist.append(el)

In [21]:
newlist

[1, 5]

In [ ]:
#  [True, False, True]
# boolean mask that tells us which ones are true or false

In [23]:
b = np.array([2, 3, 4, 5])
should_include_elements = np.array([False, True, False, True])

In [24]:
should_include_elements

array([False,  True, False,  True])

In [25]:
# how do i apply this

# my thing   => b
# where      => [
# condition is true => should_include_elements

In [26]:
b[should_include_elements]

array([3, 5])

In [28]:
should_include_elements = np.array([False, True, True])
matrix[should_include_elements]

array([[4, 5, 6],
       [7, 8, 9]])

# Arrays of Booleans == Beating Heart of Filterin/Transforming Arrays
  * This is how we can do loop-like stuff w/o loops
  * This 'spell' is called 'Boolean Masking' and folks may 'array filtering' or 'indexing'

In [31]:
# pep8:
# typical structure:
# spaces between elements,
# spaces between assignments var = thing_into_var
# ^not when you are denoting arguments in a function
# x = 5
# my_funct(x=5)

In [29]:
x = np.array([1, 2, 3, 4,5])

In [30]:
x == 3

array([False, False,  True, False, False])

In [32]:
smalllist == 3

False

In [34]:
x < -9

array([False, False, False, False, False])

In [36]:
x % 2 == 0

array([False,  True, False,  True, False])

In [37]:
# we don't need the extra variable, however, we cando the following:
# I read this code almost liike SQL in my head:
# SELECT X where X is equal to 3
x[x==3]

array([3])

In [38]:
# SELECT X where X is less than 0
x[x<0]

array([], dtype=int64)

In [40]:
x[x%2==0]

array([2, 4])

In [49]:
# remove evens
def remove_evens(x):
    x = np.array(x)
    r = x[x%2==0]
    return r

In [50]:
y = []
for i in range (1,101):
    y.append(i)
    

In [52]:
remove_evens(y)


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [54]:
# vectorized operations assert in the same way that we ituluzed coolwan masking:

In [56]:
smalllist

[1, 3, 5]

In [58]:
[x+ 1 for x in smalllist]

[2, 4, 6]

In [61]:
x + 1

array([2, 3, 4, 5, 6])

In [63]:
x = np.random.randint(1, 21, 10)
x

array([13, 12,  9,  3, 17, 16,  3, 13,  6, 15])

In [65]:
x.shape

(10,)

In [76]:
x = np.random.randint(1, 21, 10)
x

array([17, 16,  9,  7, 13,  4,  9, 12,  1, 12])

In [78]:
# Leat's make Python fall on its face
a =[1, 2, 3]

# In Python, how would we add one to every item on this list?
[n+1 for n in a]

[2, 3, 4]

In [83]:
np.array(a) +1

array([2, 3, 4])

In [85]:
x - 2*x

array([-17, -16,  -9,  -7, -13,  -4,  -9, -12,  -1, -12])

In [88]:
beatles = ['Ringo', 'John', 'Paul', 'George']

In [90]:
beatles = np.array(beatles)

In [92]:
beatles != 'Ringo'

array([False,  True,  True,  True])

In [94]:
beatles[beatles != 'Ringo']

array(['John', 'Paul', 'George'], dtype='<U6')

In [96]:
matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [98]:
beatles * 2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U6'), dtype('int64')) -> None

In [99]:
'Ringo' * 2

'RingoRingo'